//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.03.26 at 05:49:30 PM CEST
//

package org.emau.icmvc.ganimed.ttp.cm2.config;

/*-
 * ###license-information-start###
 * E-PIX - Enterprise Patient Identifier Cross-referencing
 * __
 * Copyright (C) 2014 - 2024 Trusted Third Party of the University Medicine Greifswald -
 * 							kontakt-ths@uni-greifswald.de
 * 
 * 							concept and implementation
 * 							l.geidel, c.hampf
 * 							web client
 * 							a.blumentritt, m.bialke, f.m.moser
 * 							fhir-api
 * 							m.bialke
 * 							docker
 * 							r. schuldt
 * 
 * 							The gICS was developed by the University Medicine Greifswald and published
 * 							in 2014 as part of the research project "MOSAIC" (funded by the DFG HO 1937/2-1).
 * 
 * 							Selected functionalities of gICS were developed as
 * 							part of the following research projects:
 * 							- MAGIC (funded by the DFG HO 1937/5-1)
 * 							- MIRACUM (funded by the German Federal Ministry of Education and Research 01ZZ1801M)
 * 							- NUM-CODEX (funded by the German Federal Ministry of Education and Research 01KX2021)
 * 
 * 							please cite our publications
 * 							https://doi.org/10.1186/s12911-022-02081-4
 * 							https://doi.org/10.1186/s12967-020-02457-y
 * 							http://dx.doi.org/10.3414/ME14-01-0133
 * 							http://dx.doi.org/10.1186/s12967-015-0545-6
 * 							http://dx.doi.org/10.3205/17gmds146
 * __
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * ###license-information-end###
 */

import javax.xml.namespace.QName;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import org.emau.icmvc.ganimed.ttp.cm2.config.qc.QCProblemType;
import org.emau.icmvc.ganimed.ttp.cm2.config.qc.QCProblemTypeAction;
import org.emau.icmvc.ganimed.ttp.cm2.config.qc.QCType;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated
 * in this package.
 * <p>
 * An ObjectFactory allows you to programmatically construct new instances of the Java representation for XML
 * content. The Java representation of XML content can consist of schema derived interfaces and classes
 * representing the binding of schema type definitions, element declarations and model groups. Factory methods
 * for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory
{
	public static final String NAME_SPACE = "http://www.ttp.ganimed.icmvc.emau.org/cm2/config";
	public static final String NAME = "DomainConfig";
	private static final QName _DomainConfig_QNAME = new QName(NAME_SPACE, NAME);

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * org.emau.icmvc.ganimed.ttp.cm2.config
	 */
	public ObjectFactory()
	{
		// needed by the framework
	}

	/**
	 * Create an instance of {@link JAXBElement } {@code <}{@link DomainConfig }{@code >}
	 */
	@XmlElementDecl(namespace = NAME_SPACE, name = NAME)
	public JAXBElement<DomainConfig> createDomainConfig(DomainConfig value)
	{
		return new JAXBElement<>(_DomainConfig_QNAME, DomainConfig.class, null, value);
	}

	/**
	 * Create an instance of {@link QualityControlConfig }
	 */
	public QualityControlConfig createQualityControlConfig()
	{
		return new QualityControlConfig();
	}

	/**
	 * Create an instance of {@link StatisticConfig }
	 */
	public StatisticConfig createStatisticConfig()
	{
		return new StatisticConfig();
	}

	/**
	 * Create an instance of {@link PoliciesConfig }
	 */
	public PoliciesConfig createPoliciesConfig()
	{
		return new PoliciesConfig();
	}

	/**
	 * Create an instance of {@link ScansConfig }
	 */
	public ScansConfig createScansConfig()
	{
		return new ScansConfig();
	}

	/**
	 * Create an instance of {@link NotificationsConfig }
	 */
	public NotificationsConfig createNotificationsConfig()
	{
		return new NotificationsConfig();
	}

	/**
	 * Create an instance of {@link QCType }
	 */
	public QCType createQCType()
	{
		return new QCType();
	}

	/**
	 * Create an instance of {@link QCProblemType }
	 */
	public QCProblemType createQCProblemType()
	{
		return new QCProblemType();
	}

	/**
	 * Create an instance of {@link QCProblemTypeAction }
	 */
	public QCProblemTypeAction createQCProblemTypeAction()
	{
		return new QCProblemTypeAction();
	}
}
