<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>gics-project</artifactId>
		<groupId>org.emau.icmvc.ganimed.ttp</groupId>
		<version>2024.3.0</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>gics-coverage</artifactId>
	<name>gics-coverage</name>

	<dependencies>
		<dependency>
			<groupId>org.emau.icmvc.ganimed.ttp</groupId>
			<artifactId>gics-commons</artifactId>
		</dependency>
		<dependency>
			<groupId>org.emau.icmvc.ganimed.ttp</groupId>
			<artifactId>gics-ejb</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>org.emau.icmvc.ganimed.ttp</groupId>
			<artifactId>gics-web</artifactId>
			<version>${project.parent.version}</version>
			<type>war</type>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.8.12</version>
				<executions>
					<!-- aggregated overall test coverage report -->
					<execution>
						<id>aggregate-reports</id>
						<phase>test</phase>
						<goals>
							<goal>report-aggregate</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.reporting.outputDirectory}/jacoco</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
