<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.emau.icmvc.ganimed.ttp</groupId>
	<artifactId>gics-project</artifactId>
	<version>2024.3.0</version>
	<name>gICS</name>
	<url>https://www.ths-greifswald.de/gics</url>

	<packaging>pom</packaging>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<ttp-web-common.version>2024.3.0</ttp-web-common.version>
		<ths-utils.version>1.5.4</ths-utils.version>
		<project.shortName>gics</project.shortName>
		<project.upperName>GICS</project.upperName>
		<display_version>${project.version}</display_version>
		<log4j.version>2.24.2</log4j.version>
		<ttp-noti.version>2024.1.1</ttp-noti.version>
		<ttp-gras.version>1.2.0</ttp-gras.version>
		<docker-shared-resources.version>2024.2.0</docker-shared-resources.version>
		<hapi-fhir.version>7.6.0</hapi-fhir.version><!-- json export fails on higher versions -->
		<excludeTests>Disabled,Integration,Selenium</excludeTests>
	</properties>
	<modules>
		<module>gics-commons</module>
		<module>gics-ejb</module>
		<module>gics-ear</module>
		<module>gics-web</module>
		<module>gics-docker</module>
		<module>gics-coverage</module>
	</modules>

	<profiles>
		<profile>
			<id>dev</id>
			<properties>
				<display_version>${project.version} - Branch: ${env.CI_COMMIT_REF_NAME} - Built: ${maven.build.timestamp} UTC
				</display_version>
				<maven.build.timestamp.format>yyyy-MM-dd HH:mm</maven.build.timestamp.format>
			</properties>
		</profile>
		<profile>
			<id>demo</id>
			<properties>
				<disclaimer.enable.start>--&gt;</disclaimer.enable.start>
				<disclaimer.enable.end>&lt;!--</disclaimer.enable.end>
				<display_version>${project.version} - Demo</display_version>
			</properties>
		</profile>
		<profile>
			<id>staticContext</id>
			<properties>
				<!--suppress UnresolvedMavenProperty -->
				<env.TTP_GICS_WEB_CONTEXT>${project.shortName}-web</env.TTP_GICS_WEB_CONTEXT>
				<!--suppress UnresolvedMavenProperty -->
				<env.TTP_GICS_SOAP_CONTEXT>${project.shortName}</env.TTP_GICS_SOAP_CONTEXT>
			</properties>
		</profile>
		<profile>
			<id>secured</id>
			<properties>
				<login.enable.start>--&gt;</login.enable.start>
				<login.enable.end>&lt;!--</login.enable.end>
				<gras-login.enable.start>--&gt;</gras-login.enable.start>
				<gras-login.enable.end>&lt;!--</gras-login.enable.end>
			</properties>
		</profile>
		<profile>
			<id>coverage</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<version>0.8.12</version>
						<executions>
							<execution>
								<goals>
									<goal>prepare-agent</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<!-- profiles for testing -->
		<profile>
			<id>integration</id>
			<properties>
				<excludeTests>Disabled</excludeTests>
			</properties>
			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-surefire-plugin</artifactId>
							<configuration>
								<groups>Integration</groups>
							</configuration>
						</plugin>
					</plugins>
				</pluginManagement>
			</build>
		</profile>
		<profile>
			<id>selenium</id>
			<properties>
				<excludeTests>Disabled</excludeTests>
			</properties>
			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-surefire-plugin</artifactId>
							<configuration>
								<groups>Selenium</groups>
							</configuration>
						</plugin>
					</plugins>
				</pluginManagement>
			</build>
		</profile>
	</profiles>

	<repositories>
		<repository>
			<id>ttp-releases</id>
			<name>Trusted Third Party Maven Repository</name>
			<url>https://nexus.icm.med.uni-greifswald.de/repository/maven-releases-extern</url>
		</repository>
		<!-- Required for barcode4j-light 2.1-->
		<repository>
			<id>prime-repo</id>
			<name>PrimeFaces Maven Repository</name>
			<url>https://repository.primefaces.org</url>
		</repository>
	</repositories>

	<dependencyManagement>
		<dependencies>
			<!-- gICS -->
			<dependency>
				<groupId>org.emau.icmvc.ganimed.ttp</groupId>
				<artifactId>gics-commons</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ganimed.ttp</groupId>
				<artifactId>gics-ejb</artifactId>
				<version>${project.version}</version>
				<type>ejb</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ganimed.ttp</groupId>
				<artifactId>gics-shared-resources</artifactId>
				<version>${project.version}</version>
				<type>jar</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ganimed.ttp</groupId>
				<artifactId>gics-ear</artifactId>
				<version>${project.version}</version>
				<type>ear</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ganimed.ttp</groupId>
				<artifactId>gics-web</artifactId>
				<version>${project.version}</version>
				<type>war</type>
			</dependency>

			<!-- TTP utils and shared resources -->
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ths-utils</artifactId>
				<version>${ths-utils.version}</version>
				<type>jar</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ttp-web-common</artifactId>
				<version>${ttp-web-common.version}</version>
				<type>war</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ttp-web-common</artifactId>
				<version>${ttp-web-common.version}</version>
				<classifier>classes</classifier>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>noti-shared-resources</artifactId>
				<version>${ttp-noti.version}</version>
				<type>jar</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ths-notification-client-ear</artifactId>
				<version>${ttp-noti.version}</version>
				<type>ear</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ths-notification-service</artifactId>
				<version>${ttp-noti.version}</version>
				<type>war</type>
			</dependency>
			<dependency>
				<groupId>org.icmvc.ttp</groupId>
				<artifactId>gras-shared-resources</artifactId>
				<version>${ttp-gras.version}</version>
				<type>jar</type>
			</dependency>
			<dependency>
				<groupId>org.icmvc.ttp.docker</groupId>
				<artifactId>docker-shared-resources</artifactId>
				<version>${docker-shared-resources.version}</version>
				<type>jar</type>
			</dependency>

			<!-- Logging -->
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-api</artifactId>
				<version>${log4j.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-api</artifactId>
				<version>2.0.16</version>
				<scope>provided</scope>
			</dependency>

			<!-- JavaEE APIs -->
			<dependency>
				<groupId>jakarta.platform</groupId>
				<artifactId>jakarta.jakartaee-api</artifactId>
				<version>10.0.0</version>
				<scope>provided</scope>
			</dependency>

			<!-- Apache Commons -->
			<dependency>
				<groupId>commons-codec</groupId>
				<artifactId>commons-codec</artifactId>
				<version>1.17.1</version>
			</dependency>

			<!-- Notifications -->
			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-databind</artifactId>
				<version>2.18.2</version>
				<scope>provided</scope>
			</dependency>

			<!-- Persistence -->
			<dependency>
				<groupId>org.eclipse.persistence</groupId>
				<artifactId>eclipselink</artifactId>
				<version>4.0.4</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.eclipse.persistence</groupId>
				<artifactId>org.eclipse.persistence.jpa.modelgen.processor</artifactId>
				<version>4.0.4</version>
				<scope>provided</scope>
				<exclusions>
					<exclusion>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-core</artifactId>
					</exclusion>
				</exclusions>
			</dependency>

			<!-- Web -->
			<dependency>
				<groupId>org.primefaces</groupId>
				<artifactId>primefaces</artifactId>
				<version>14.0.8</version>
				<scope>provided</scope>
				<classifier>jakarta</classifier>
			</dependency>
			<dependency>
				<groupId>software.xdev</groupId>
				<artifactId>chartjs-java-model</artifactId>
				<version>2.5.0</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>com.ibm.icu</groupId>
				<artifactId>icu4j</artifactId>
				<version>76.1</version>
			</dependency>
			<dependency>
				<groupId>ca.uhn.hapi.fhir</groupId>
				<artifactId>hapi-fhir-structures-r4</artifactId>
				<version>${hapi-fhir.version}</version>
			</dependency>
			<!-- Barcodes in primefaces -->
			<dependency>
				<groupId>io.nayuki</groupId>
				<artifactId>qrcodegen</artifactId>
				<!-- Warning: Only use the exact version that is required by primefaces -->
				<version>1.8.0</version>
			</dependency>
			<dependency>
				<groupId>org.primefaces.extensions</groupId>
				<artifactId>barcode4j-light</artifactId>
				<version>2.3.0</version>
			</dependency>
			<!-- Template parsing -->
			<dependency>
				<groupId>com.google.zxing</groupId>
				<artifactId>core</artifactId>
				<version>3.5.3</version>
			</dependency>
			<dependency>
				<groupId>com.google.zxing</groupId>
				<artifactId>javase</artifactId>
				<version>3.5.3</version>
			</dependency>
			<dependency>
				<groupId>org.apache.pdfbox</groupId>
				<artifactId>pdfbox</artifactId>
				<version>2.0.32</version>
			</dependency>
			<!-- PDF Generation (do not set scope to test!) -->
			<dependency>
				<groupId>org.seleniumhq.selenium</groupId>
				<artifactId>selenium-java</artifactId>
				<version>4.27.0</version>
			</dependency>

			<!-- Java 9+ Kompatibilität -->
			<dependency>
				<groupId>com.sun.xml.ws</groupId>
				<artifactId>jaxws-rt</artifactId>
				<version>4.0.3</version>
				<type>pom</type>
				<!-- implicitly provides jaxb-core for gics-commons -->
			</dependency>

			<!-- Other -->
			<dependency>
				<groupId>org.aspectj</groupId>
				<artifactId>aspectjweaver</artifactId>
				<version>1.9.22.1</version>
				<scope>runtime</scope>
			</dependency>
			<dependency>
				<groupId>org.aspectj</groupId>
				<artifactId>aspectjrt</artifactId>
				<version>1.9.22.1</version>
			</dependency>
			<dependency>
				<groupId>com.wutka</groupId>
				<artifactId>dtdparser</artifactId>
				<version>1.21</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.mvel</groupId>
				<artifactId>mvel2</artifactId>
				<version>2.5.2.Final</version>
			</dependency>
			
			<!-- Tests -->
			<dependency>
				<groupId>ch.qos.logback</groupId>
				<artifactId>logback-core</artifactId>
				<version>1.5.12</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>ch.qos.logback</groupId>
				<artifactId>logback-classic</artifactId>
				<version>1.5.12</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-frontend-jaxws</artifactId>
				<scope>test</scope>
				<version>4.0.5</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-transports-http-jetty</artifactId>
				<scope>test</scope>
				<version>4.0.5</version>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-core</artifactId>
				<version>${log4j.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ttp-web-common</artifactId>
				<version>${ttp-web-common.version}</version>
				<type>test-jar</type>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter</artifactId>
				<version>5.11.3</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-core</artifactId>
				<version>5.14.2</version>
				<scope>test</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>3.4.2</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-ejb-plugin</artifactId>
					<version>3.2.1</version>
					<configuration>
						<ejbVersion>3.2</ejbVersion>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-ear-plugin</artifactId>
					<version>3.3.0</version>
					<configuration>
						<version>6</version>
						<filtering>true</filtering>
						<jboss>
							<version>5</version>
						</jboss>
						<defaultLibBundleDir>lib</defaultLibBundleDir>
						<applicationName>${project.shortName}</applicationName>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.13.0</version>
					<configuration>
						<source>21</source>
						<target>21</target>
						<debug>true</debug>
						<debuglevel>source,lines,vars</debuglevel>
						<generatedSourcesDirectory>target/generated-sources/annotations</generatedSourcesDirectory>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-war-plugin</artifactId>
					<version>3.4.0</version>
					<configuration>
						<archive>
							<manifestEntries>
								<Dependencies>org.slf4j,deployment.${project.shortName}-ear-${project.version}.ear</Dependencies>
							</manifestEntries>
						</archive>
						<nonFilteredFileExtensions>
							<nonFilteredFileExtension>gif</nonFilteredFileExtension>
							<nonFilteredFileExtension>ico</nonFilteredFileExtension>
							<nonFilteredFileExtension>jpg</nonFilteredFileExtension>
							<nonFilteredFileExtension>png</nonFilteredFileExtension>
							<nonFilteredFileExtension>pdf</nonFilteredFileExtension>
						</nonFilteredFileExtensions>
						<webResources>
							<resource>
								<directory>src/main/webapp</directory>
								<filtering>true</filtering>
							</resource>
						</webResources>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-deploy-plugin</artifactId>
					<version>3.1.3</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.22.2</version>
					<configuration>
						<excludedGroups>${excludeTests}</excludedGroups>
						<!-- to disable a java.lang.AssertionError at ca.uhn.fhir.parser.path.EncodeContextPath.pushPath(EncodeContextPath.java:86) -->
						<enableAssertions>false</enableAssertions>
					</configuration>
				</plugin>
				<plugin>
					<!--To update license details, set canUpdateCopyright to true and run with maven goal 'license:update-file-header' -->
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>license-maven-plugin</artifactId>
					<!-- Warning: Higher versions dont work for now -->
					<version>1.20</version>
					<configuration>
						<canUpdateCopyright>false</canUpdateCopyright>
						<verbose>false</verbose>
						<processStartTag>###license-information-start###</processStartTag>
						<processEndTag>###license-information-end###</processEndTag>
						<sectionDelimiter>__</sectionDelimiter>
						<projectName>gICS - a Generic Informed Consent Service</projectName>
						<inceptionYear>2014</inceptionYear>
						<organizationName>Trusted Third Party of the University Medicine Greifswald -
							kontakt-ths@uni-greifswald.de

							concept and implementation
							l.geidel, c.hampf
							web client
							a.blumentritt, m.bialke, f.m.moser
							fhir-api
							m.bialke
							docker
							r. schuldt

							The gICS was developed by the University Medicine Greifswald and published
							in 2014 as part of the research project "MOSAIC" (funded by the DFG HO 1937/2-1).

							Selected functionalities of gICS were developed as
							part of the following research projects:
							- MAGIC (funded by the DFG HO 1937/5-1)
							- MIRACUM (funded by the German Federal Ministry of Education and Research 01ZZ1801M)
							- NUM-CODEX (funded by the German Federal Ministry of Education and Research 01KX2021)

							please cite our publications
							https://doi.org/10.1186/s12911-022-02081-4
							https://doi.org/10.1186/s12967-020-02457-y
							http://dx.doi.org/10.3414/ME14-01-0133
							http://dx.doi.org/10.1186/s12967-015-0545-6
							http://dx.doi.org/10.3205/17gmds146
						</organizationName>
						<licenseName>agpl_v3</licenseName>
						<excludes>
							<exclude>**/beans.xml</exclude>
							<exclude>**/*.json</exclude>
							<exclude>**/Dockerfile*</exclude>
						</excludes>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>3.6.3</version>
					<configuration>
						<windowtitle>gICS ${project.version} API</windowtitle>
						<bottom><![CDATA[gICS ${project.version} API, Copyright 2024, <a href="https://www.ths-greifswald.de">ths-greifswald.de<a>]]></bottom>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
