version: '2'
services:

### WildFly #############################################
  wildfly:
    image: mosaicgreifswald/wildfly:18.0.1.Final-20191213
    container_name: gicsApp   
    environment:      
      JAVA_OPTS: '-server -Xms1G -Xmx6G -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=1G -XX:StringTableSize=1000003 -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman' 
    volumes:
      - ./jboss:/entrypoint-jboss-batch
      - ./deployments:/entrypoint-deployments
    entrypoint: /bin/bash