CREATE TABLE mapped_consent_template
(
    FROM_NAME varchar(100) NOT NULL,
    FROM_DOMAIN_NAME varchar(50) NOT NULL,
    FROM_VERSION int NOT NULL,
    TO_NAME varchar(100) NOT NULL,
    TO_DOMAIN_NAME varchar(50) NOT NULL,
    TO_VERSION int NOT NULL,
    CONSTRAINT C_PRIMARY PRIMARY KEY (FROM_NAME,FROM_DOMAIN_NAME,FROM_VERSION,TO_NAME,TO_DOMAIN_NAME,TO_VERSION)
) collate utf8_bin
;
